import React from 'react';
import {stopList, inverted_indexes, TagsNeeded} from '../variables/variables';

let timeRunning  = 0;
export const parseXML = (insertFile) => {
    let begin = new Date();
    const parser = new DOMParser();
    const dom = parser.parseFromString(insertFile, "application/xml");

    let records = new Set();
    records = dom.getElementsByTagName("RECORD");

    // find needed tags
    let autoGeneratedId = 0;
    for (const record of records){
        let record_id = record.getElementsByTagName("RECORDNUM")[0] == undefined ? autoGeneratedId : record.getElementsByTagName("RECORDNUM")[0].childNodes[0].data;
        autoGeneratedId++; // increment autoGeneratedId to record the sequence of doc being read
        for (const tag of record.getElementsByTagName("*")){
            let tagName = tag.tagName;
            if(TagsNeeded.has(tagName)){ // if tag is in the NotNeeded set, tokenize it
                tokenizing(record_id, record.getElementsByTagName(tagName)[0].childNodes[0].data)
            }
        }
    }

    const sorted = [];
    for(const key in inverted_indexes) {
        sorted[sorted.length] = key;
    }
    sorted.sort();
    let end = new Date();
    timeRunning = (end - begin)/1000;
    return sorted
}

export const getRunTime = () => {
    return timeRunning;
}

export const tokenizing = (record_id, paragraph) => {
    let words = paragraph.split(/[\[\]<>.,\/#!$%\^&\*;:{}=_()?@\s\"]/g); //remove punctuation marks
    for (let word of words){
        word = word.toLowerCase();
        //word = word.replace(/[0-9]/g, '');
        word = word.replace(/[\-_~\'\d+]/g,"") // remove hypens and apostrophies
        if(word == null || word.length==0 || stopList.includes(word)){
            continue;
        }
        else{
            indexing(record_id, word);
        }
    }
}

export const indexing = (record_id, word) => {
    let list = (word in inverted_indexes) ? inverted_indexes[word]:[]
    if (!list.includes(record_id)){
        list.push(record_id);
        inverted_indexes[word] = list;
        console.log(list)
    }
}

export default {
    parseXML, getRunTime
}